"use client";
import { useEffect, useState } from "react";
import BrandSelect from "@/components/BrandSelect";
import DashboardSkeleton from "@/components/DashboardSkeleton";

type Withdrawal = { id: string; amount: number; fee_amount: number; net_amount: number; method: string; destination: string; status: string; created_at: string };
export default function WithdrawalsPage() {
  const [available, setAvailable] = useState(0); const [items, setItems] = useState<Withdrawal[]>([]); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true);
  const load = async () => { const response = await fetch("/api/dashboard", { cache: "no-store" }); if (response.status === 401) { location.href = "/login"; return; } const data = await response.json(); setAvailable(Number(data.stats?.available || 0)); setItems(data.withdrawals || []); setLoading(false); };
  useEffect(() => { const timer = window.setTimeout(() => { load(); }, 0); return () => window.clearTimeout(timer); }, []);
  const submit = async (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); setSaving(true); const payload = Object.fromEntries(new FormData(e.currentTarget)); const response = await fetch("/api/dashboard", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); setNotice(response.ok ? `Demande envoyée : ${Number(data.fees.net).toLocaleString("fr-FR")} FCFA nets.` : data.error || "Demande impossible"); if (response.ok) { e.currentTarget.reset(); load(); } setSaving(false); };
  if (loading) return <DashboardSkeleton compact />;
  return <main className="min-h-[calc(100vh-4rem)] px-5 py-8 sm:px-8"><div className="mx-auto max-w-5xl"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-[#b20024]">Votre espace créateur</p><h1 className="mt-2 text-3xl font-bold">Retraits</h1><p className="mt-1 text-sm text-[#6f5a57]">Demandez le versement de votre solde vers Mobile Money ou crypto.</p></div><p className="rounded-xl bg-[#edf6ee] px-4 py-3 text-sm font-bold text-[#315c38]">{available.toLocaleString("fr-FR")} FCFA disponibles</p></header>{notice && <p className="mt-6 rounded-xl bg-[#fff2f1] px-4 py-3 text-sm font-semibold text-[#8e001d]">{notice}</p>}<section className="mt-7 rounded-2xl border border-[#ead6d2] bg-white p-6 shadow-[0_10px_24px_rgba(91,64,63,0.05)]"><h2 className="text-xl font-bold">Nouveau retrait</h2><p className="mt-1 text-sm text-[#6f5a57]">Frais Buy Me Data : 11 % du montant demandé.</p><form onSubmit={submit} className="mt-5 grid gap-3 sm:grid-cols-2"><input name="amount" type="number" min={500} max={available || undefined} required placeholder="Montant en FCFA" className="rounded-xl border border-[#ead6d2] px-4 py-3" /><BrandSelect name="method" label="Mode de retrait" defaultValue="mobile_money" options={[{value:"mobile_money",label:"Mobile Money"},{value:"crypto",label:"Crypto"}]}/><input name="destination" required placeholder="Numéro Mobile Money ou adresse crypto" className="rounded-xl border border-[#ead6d2] px-4 py-3 sm:col-span-2" /><button disabled={saving || available < 500} className="rounded-xl bg-[#b20024] px-5 py-3 text-sm font-bold text-white disabled:opacity-40">{saving ? "Envoi…" : "Demander un retrait"}</button></form></section><section className="mt-5 rounded-2xl border border-[#ead6d2] bg-white p-6 shadow-[0_10px_24px_rgba(91,64,63,0.05)]"><h2 className="text-xl font-bold">Historique</h2><div className="mt-4 space-y-3">{items.length === 0 ? <p className="rounded-xl bg-[#fbf9f4] px-4 py-6 text-center text-sm text-[#6f5a57]">Aucune demande de retrait.</p> : items.map(item => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-[#fbf9f4] px-4 py-3 text-sm"><div><p className="font-semibold">{item.method === "crypto" ? "Crypto" : "Mobile Money"} · {item.destination}</p><p className="mt-1 text-xs text-[#6f5a57]">{new Date(item.created_at).toLocaleDateString("fr-FR")}</p></div><div className="text-right"><p className="font-bold">{Number(item.net_amount).toLocaleString("fr-FR")} FCFA</p><p className="text-xs text-[#6f5a57]">{item.status}</p></div></div>)}</div></section></div></main>;
}
