"use client";
import {useState} from "react";
import Link from "next/link";
import {TopUpLogo} from "@/components/Navbar";
export default function ForgotPassword(){
 const [email,setEmail]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await fetch("/api/auth/forgot-password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage(d.message);}catch(e){setError(e instanceof Error?e.message:"Veuillez réessayer.");}finally{setBusy(false);}}
 return <main className="grid min-h-screen place-items-center bg-[#fbf9f4] p-5"><section className="w-full max-w-md rounded-3xl border border-[#ead6d2] bg-white p-7 shadow-xl sm:p-9"><Link href="/" className="mb-8 flex items-center gap-3 font-bold text-[#b20024]"><TopUpLogo className="h-10 w-10"/>Buy Me Data</Link><h1 className="text-3xl font-bold">Mot de passe oublié</h1><p className="mt-2 text-sm leading-6 text-[#6f5a57]">Entrez l’adresse de votre compte. Le lien reçu sera valable 30 minutes.</p>{message&&<p role="status" className="mt-5 rounded-xl bg-[#edf6ee] p-4 text-sm text-[#315c38]">{message}</p>}{error&&<p role="alert" className="mt-5 rounded-xl bg-[#fff2f1] p-4 text-sm text-[#b20024]">{error}</p>}<form onSubmit={submit} className="mt-6"><label className="text-xs font-bold uppercase tracking-wider text-[#5b403f]">Adresse e-mail<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-2 w-full rounded-xl border border-[#e4bdbc] bg-[#fbf9f4] px-4 py-3.5 text-sm outline-none focus:border-[#b20024]"/></label><button disabled={busy} className="mt-5 w-full rounded-xl bg-[#b20024] px-4 py-4 font-bold text-white disabled:opacity-50">{busy?"Envoi…":"Recevoir le lien"}</button></form><p className="mt-6 text-center text-sm"><Link href="/login" className="font-bold text-[#b20024]">← Retour à la connexion</Link></p></section></main>;
}
