import PublicInfo from "@/components/PublicInfo";
import Link from "next/link";
export const metadata = { title: "Politique de confidentialité · Buy Me Data" };
export default function PrivacyPage() {
  return <PublicInfo title="Politique de confidentialité">
    <p>Cette politique décrit les données utilisées par Buy Me Data pour fournir les pages de soutien, les cagnottes et les comptes créateurs. Pour toute demande concernant vos données, utilisez notre <Link href="/contact">page Contact</Link>.</p>
    <h2>Données que vous fournissez</h2><p>Lors de l’inscription, nous utilisons votre adresse e-mail, votre username et un mot de passe stocké sous forme de hachage. Votre nom public, votre photo et votre présentation servent à personnaliser votre page. Les pages publiques rendent visibles ces informations ainsi que les cagnottes que vous publiez.</p>
    <h2>Connexion avec Google</h2><p>Si vous choisissez Google, nous demandons les informations de base nécessaires à la connexion : identifiant Google, adresse e-mail vérifiée, nom et photo de profil. Nous ne demandons pas l’accès à votre boîte Gmail, à vos contacts ou à Google Drive. Les données Google servent à identifier et sécuriser votre compte, pas à diffuser des publicités personnalisées.</p>
    <h2>Contributions et paiements</h2><p>Pour traiter un soutien, nous conservons son montant, sa référence, son statut, le créateur bénéficiaire et, si vous les fournissez, votre nom, votre e-mail et votre message. Le paiement peut être effectué sans compte. Les informations nécessaires au paiement sont transmises au prestataire sélectionné, WaraPay ou TaraMoney. Les données de carte saisies sur leur interface ne sont pas collectées par notre formulaire.</p>
    <h2>Pourquoi nous utilisons ces données</h2><p>Elles permettent de gérer votre compte, d’afficher vos pages, de confirmer les paiements, de traiter les retraits et vos demandes d’assistance, et de prévenir les abus. Les traitements nécessaires au service reposent sur son exécution ; les mesures de sécurité reposent sur l’intérêt légitime de protéger le service ; certaines données peuvent être conservées pour répondre aux obligations applicables.</p>
    <h2>Cookies et destinataires</h2><p>Nous utilisons des cookies techniques pour la session et la sécurité de la connexion Google. Les prestataires d’hébergement, d’e-mail et de paiement peuvent traiter les données nécessaires à leurs fonctions. Selon leur infrastructure, ce traitement peut avoir lieu dans un autre pays. Les données ne sont pas mises en vente par Buy Me Data.</p>
    <h2>Conservation et sécurité</h2><p>Les informations du compte sont conservées pour fournir le service. Les liens de confirmation expirent et ne peuvent être utilisés qu’une fois. Les données de transaction peuvent devoir être conservées après une demande de suppression pour la gestion des litiges et les obligations légales. Nous limitons l’accès aux données et utilisons HTTPS et des mots de passe hachés.</p>
    <h2>Vos demandes</h2><p>Vous pouvez demander l’accès, la correction ou la suppression de vos données et, selon les règles applicables, leur portabilité ou vous opposer à certains usages. Contactez-nous depuis l’adresse associée à votre compte ; une vérification d’identité proportionnée peut être nécessaire. Retirer l’accès dans votre compte Google n’efface pas automatiquement votre compte Buy Me Data.</p>
    <h2>Évolutions</h2><p>Cette page sera mise à jour si les pratiques de traitement changent. Pour une question sur son contenu, <Link href="/contact">contactez-nous</Link>.</p>
  </PublicInfo>;
}
