"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

type Campaign = { id: string; slug?: string; cover_url?: string; title: string; description?: string; target_amount: number; collected_amount: number; status: string };

export default function CampaignsPage() {
  const [campaigns, setCampaigns] = useState<Campaign[]>([]);
  const [openMenu, setOpenMenu] = useState<string | null>(null);
  const [notice, setNotice] = useState("");
  const load = async () => { const response = await fetch("/api/campaigns", { cache: "no-store" }); if (response.status === 401) { location.href = "/login"; return; } setCampaigns((await response.json()).campaigns || []); };
  useEffect(() => { const timer = window.setTimeout(() => { load(); }, 0); return () => window.clearTimeout(timer); }, []);
  const campaignUrl = (campaign: Campaign) => `${location.origin}/c/${campaign.slug || campaign.id}`;
  const copy = async (campaign: Campaign) => { await navigator.clipboard?.writeText(campaignUrl(campaign)); setOpenMenu(null); setNotice("Lien de cagnotte copié."); };
  const remove = async (id: string) => { if (!confirm("Supprimer cette cagnotte sans don ?")) return; const response = await fetch(`/api/campaigns/${id}`, { method: "DELETE" }); const body = await response.json(); setNotice(response.ok ? "Cagnotte supprimée." : body.error || "Suppression impossible"); if (response.ok) load(); };
  return <main className="min-h-[calc(100vh-4rem)] px-5 py-8 sm:px-8"><div className="mx-auto max-w-5xl"><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-bold text-[#b20024]">Votre espace créateur</p><h1 className="mt-2 text-3xl font-bold">Mes cagnottes</h1><p className="mt-1 text-sm text-[#6f5a57]">Créez, partagez et pilotez chaque objectif.</p></div><Link href="/dashboard/create-campaign" className="rounded-xl bg-[#b20024] px-5 py-3 text-sm font-bold text-white">Créer une cagnotte</Link></header>{notice && <p className="mt-6 rounded-xl bg-[#fff2f1] px-4 py-3 text-sm font-semibold text-[#8e001d]">{notice}</p>}<div className="mt-7 space-y-4">{campaigns.length === 0 ? <div className="rounded-2xl border border-dashed border-[#dec9c4] bg-white p-10 text-center"><p className="font-bold">Aucune cagnotte créée</p><Link href="/dashboard/create-campaign" className="mt-4 inline-block text-sm font-bold text-[#b20024]">Créer mon premier objectif</Link></div> : campaigns.map(c => <CampaignCard key={c.id} campaign={c} open={openMenu === c.id} onToggle={() => setOpenMenu(openMenu === c.id ? null : c.id)} onCopy={() => copy(c)} onRemove={() => remove(c.id)} url={campaignUrl(c)} />)}</div></div></main>;
}

function CampaignCard({ campaign: c, open, onToggle, onCopy, onRemove, url }: { campaign: Campaign; open: boolean; onToggle: () => void; onCopy: () => void; onRemove: () => void; url: string }) {
  const percent = Math.min(100, Math.round(Number(c.collected_amount) * 100 / Number(c.target_amount)));
  return <section className="overflow-visible rounded-2xl border border-[#ead6d2] bg-white shadow-[0_10px_24px_rgba(91,64,63,0.05)]"><div className="flex flex-col sm:flex-row"><div className="h-44 bg-[#fff2f1] sm:h-auto sm:w-52"><img src={c.cover_url || "/buy-me-data-mascot.png"} alt="" className="h-full w-full rounded-t-2xl object-cover sm:rounded-l-2xl sm:rounded-tr-none" /></div><div className="min-w-0 flex-1 p-5 sm:p-6"><div className="flex justify-between gap-4"><div><div className="flex flex-wrap items-center gap-3"><h2 className="text-xl font-bold">{c.title}</h2><span className="rounded-full bg-[#fff2f1] px-3 py-1 text-xs font-bold text-[#b20024]">{c.status}</span></div>{c.description && <p className="mt-2 text-sm text-[#6f5a57]">{c.description}</p>}</div><div className="relative"><button onClick={onToggle} aria-label="Actions de cagnotte" className="grid h-10 w-10 place-items-center rounded-full hover:bg-[#f5f3ee]"><span className="material-symbols-outlined">more_vert</span></button>{open && <div className="absolute right-0 top-11 z-20 w-48 rounded-xl border border-[#ead6d2] bg-white p-2 text-sm shadow-xl"><Link href={`/c/${c.slug || c.id}`} target="_blank" className="block rounded-lg px-3 py-2 hover:bg-[#f5f3ee]">Voir la page</Link><button onClick={onCopy} className="block w-full rounded-lg px-3 py-2 text-left hover:bg-[#f5f3ee]">Copier le lien</button><Link href={`/dashboard/create-campaign?edit=${c.id}`} className="block rounded-lg px-3 py-2 hover:bg-[#f5f3ee]">Modifier</Link>{Number(c.collected_amount) === 0 && <button onClick={onRemove} className="block w-full rounded-lg px-3 py-2 text-left text-[#b20024] hover:bg-[#fff2f1]">Supprimer</button>}</div>}</div></div><div className="mt-5 flex items-center gap-4"><div className="h-2 flex-1 overflow-hidden rounded-full bg-[#eadfdb]"><div className="h-full bg-[#b20024]" style={{ width: `${percent}%` }} /></div><span className="text-sm font-bold text-[#b20024]">{percent}%</span></div><p className="mt-2 text-xs text-[#6f5a57]">{Number(c.collected_amount).toLocaleString("fr-FR")} / {Number(c.target_amount).toLocaleString("fr-FR")} FCFA</p><p className="mt-3 truncate text-xs text-[#7b6864]">{url}</p></div></div></section>;
}
