"use client";
import { useEffect, useState } from "react";
import Link from "next/link";

type Profile = { full_name?: string; username?: string; category?: string; avatar_url?: string; bio?: string };

export default function SupportPageManager() {
  const [profile, setProfile] = useState<Profile | null>(null);
  const [copied, setCopied] = useState(false);
  useEffect(() => { fetch("/api/profile", { cache: "no-store" }).then(async r => { if (r.status === 401) { location.href = "/login"; return; } const d = await r.json(); setProfile(d.profile); }).catch(() => null); }, []);
  if (!profile) return <main className="mx-auto max-w-5xl px-5 py-20 text-center text-[#6f5a57]">Chargement…</main>;
  const displayName = profile.username || profile.full_name || "votre page";
  const distinctBio = profile.bio && profile.bio.trim().toLowerCase() !== displayName.trim().toLowerCase() && profile.bio.trim().toLowerCase() !== (profile.full_name || "").trim().toLowerCase() ? profile.bio : "";
  const supportUrl = profile.username ? `https://buymedata.tools-cl.com/${profile.username}/donate` : "";
  async function copyLink() { if (!supportUrl) return; await navigator.clipboard?.writeText(supportUrl); setCopied(true); window.setTimeout(() => setCopied(false), 1800); }
  return <main className="mx-auto max-w-5xl px-5 py-8 sm:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#a18d88]">Monétiser</p><h1 className="mt-2 text-3xl font-bold">Me soutenir</h1><p className="mt-2 text-sm text-[#6f5a57]">Configurez votre page de soutien et partagez-la à votre communauté.</p></div><Link href="/dashboard/settings" className="rounded-xl bg-[#b20024] px-5 py-3 text-sm font-bold text-white">Modifier ma page</Link></div><section className="mt-7 grid gap-5 lg:grid-cols-[1.1fr_0.9fr]"><div className="overflow-hidden rounded-3xl border border-[#ead6d2] bg-white shadow-[0_10px_24px_rgba(91,64,63,0.05)]"><div className="h-28 bg-[linear-gradient(120deg,#b20024,#e8b7b0_58%,#fff2f1)]"/><div className="px-6 pb-7 text-center"><img src={profile.avatar_url || "/buy-me-data-mascot.png"} alt={displayName} className="relative mx-auto -mt-12 h-24 w-24 rounded-3xl border-4 border-white bg-[#fff2f1] object-cover shadow-md"/><h2 className="mt-4 text-2xl font-bold">Soutenir {displayName}</h2>{distinctBio && <p className="mx-auto mt-4 max-w-md text-sm leading-6 text-[#5b403f]">{distinctBio}</p>}<Link href={profile.username ? `/${profile.username}/donate` : "/dashboard/settings"} target="_blank" className="mt-6 inline-flex rounded-xl border border-[#b20024] px-5 py-3 text-sm font-bold text-[#b20024]">Prévisualiser ma page</Link></div></div><div className="rounded-3xl border border-[#ead6d2] bg-white p-6 shadow-[0_10px_24px_rgba(91,64,63,0.05)]"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#a18d88]">Lien à partager</p><h2 className="mt-2 text-xl font-bold">Invitez votre communauté</h2><p className="mt-2 text-sm leading-6 text-[#6f5a57]">Ce lien ouvre directement votre page de soutien.</p><div className="mt-5 rounded-xl bg-[#fbf9f4] p-4"><p className="break-all text-sm font-semibold text-[#b20024]">{supportUrl || "Complétez votre username"}</p></div><button onClick={copyLink} disabled={!supportUrl} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#1b1c19] px-4 py-3 text-sm font-bold text-white disabled:opacity-40"><span className="material-symbols-outlined text-[18px]">{copied ? "check" : "content_copy"}</span>{copied ? "Lien copié" : "Copier le lien"}</button></div></section></main>;
}
