// Personnalisation de la page de dons : thèmes, textes et bannière.
// Partagé par la page publique et l'éditeur du dashboard pour que l'aperçu
// corresponde exactement au rendu final.

export type DonationTheme = {
  id: string;
  label: string;
  description: string;
  layout: "centered" | "left";
  page: string;
  pageImage?: string;
  surface: string;
  text: string;
  muted: string;
  border: string;
  accent: string;
  accentText: string;
  accentHover: string;
  quote: string;
  radius: string;
  avatarRadius: string;
  shadow: string;
  banner: string;
  bannerHeight: string;
  display: string;
  headlineWeight: number;
  headlineTracking: string;
  headlineTransform: "none" | "uppercase";
  eyebrow: string;
};

export const donationThemes: DonationTheme[] = [
  {
    id: "atelier",
    label: "Atelier",
    description: "Ivoire et encre, titre en serif. Éditorial et chaleureux.",
    layout: "left",
    page: "#f6f3ec",
    surface: "#fffdf8",
    text: "#1a1713",
    muted: "#7a7066",
    border: "#e6ded0",
    accent: "#b20024",
    accentText: "#ffffff",
    accentHover: "#8e001d",
    quote: "#f1ece1",
    radius: "1.5rem",
    avatarRadius: "999px",
    shadow: "0 24px 60px rgba(60, 46, 28, 0.10)",
    banner: "linear-gradient(115deg, #e9dcc4, #f3ece0 55%, #fffdf8)",
    bannerHeight: "9rem",
    display: "var(--font-display), Georgia, serif",
    headlineWeight: 600,
    headlineTracking: "-0.02em",
    headlineTransform: "none",
    eyebrow: "#a1907a",
  },
  {
    id: "eclipse",
    label: "Éclipse",
    description: "Fond nuit, accent doré. Sobre et haut de gamme.",
    layout: "centered",
    page: "#0b0b0e",
    surface: "#141419",
    text: "#f4f2ee",
    muted: "#9b978e",
    border: "#26262f",
    accent: "#e6c169",
    accentText: "#17140c",
    accentHover: "#d3ad50",
    quote: "#1c1c23",
    radius: "1.75rem",
    avatarRadius: "1.25rem",
    shadow: "0 30px 80px rgba(0, 0, 0, 0.55)",
    banner: "linear-gradient(135deg, #1d1a2b, #2e2440 45%, #4a3a2a)",
    bannerHeight: "10rem",
    display: "var(--font-display), Georgia, serif",
    headlineWeight: 500,
    headlineTracking: "-0.015em",
    headlineTransform: "none",
    eyebrow: "#8a7f68",
  },
  {
    id: "studio",
    label: "Studio",
    description: "Noir et blanc, angles nets, typographie XL. Très épuré.",
    layout: "left",
    page: "#ffffff",
    surface: "#ffffff",
    text: "#0a0a0a",
    muted: "#6b6b6b",
    border: "#0a0a0a",
    accent: "#0a0a0a",
    accentText: "#ffffff",
    accentHover: "#333333",
    quote: "#f4f4f4",
    radius: "0.25rem",
    avatarRadius: "0.25rem",
    shadow: "none",
    banner: "linear-gradient(90deg, #0a0a0a 0%, #0a0a0a 38%, #ededed 38%)",
    bannerHeight: "7rem",
    display: "inherit",
    headlineWeight: 700,
    headlineTracking: "-0.04em",
    headlineTransform: "none",
    eyebrow: "#8a8a8a",
  },
  {
    id: "aurore",
    label: "Aurore",
    description: "Dégradé clair et surfaces translucides. Léger et moderne.",
    layout: "centered",
    page: "#f4f4fb",
    pageImage: "radial-gradient(120% 90% at 12% 0%, #ffe6f0 0%, transparent 55%), radial-gradient(110% 80% at 88% 8%, #dfe8ff 0%, transparent 52%)",
    surface: "rgba(255, 255, 255, 0.72)",
    text: "#211f2b",
    muted: "#6e6a7d",
    border: "rgba(255, 255, 255, 0.85)",
    accent: "#6d4dfb",
    accentText: "#ffffff",
    accentHover: "#5a39e8",
    quote: "rgba(255, 255, 255, 0.6)",
    radius: "2rem",
    avatarRadius: "999px",
    shadow: "0 26px 70px rgba(70, 60, 130, 0.14)",
    banner: "linear-gradient(120deg, #c6b3ff, #ffc6e0 52%, #bfe0ff)",
    bannerHeight: "9rem",
    display: "inherit",
    headlineWeight: 700,
    headlineTracking: "-0.03em",
    headlineTransform: "none",
    eyebrow: "#8e87a6",
  },
  {
    id: "encre",
    label: "Encre",
    description: "Bleu nuit profond et blanc cassé. Sérieux, très lisible.",
    layout: "left",
    page: "#0f1a2b",
    surface: "#16233a",
    text: "#eef3fa",
    muted: "#9aabc4",
    border: "#24344f",
    accent: "#5aa9ff",
    accentText: "#06121f",
    accentHover: "#4793e6",
    quote: "#1d2c46",
    radius: "1.25rem",
    avatarRadius: "1rem",
    shadow: "0 28px 70px rgba(4, 12, 26, 0.5)",
    banner: "linear-gradient(120deg, #16233a, #274064 60%, #3d6799)",
    bannerHeight: "9rem",
    display: "inherit",
    headlineWeight: 700,
    headlineTracking: "-0.03em",
    headlineTransform: "none",
    eyebrow: "#6f86a6",
  },
  {
    id: "terracotta",
    label: "Terracotta",
    description: "Terres cuites et sable. Chaleureux, artisanal.",
    layout: "centered",
    page: "#fbf3ec",
    surface: "#ffffff",
    text: "#3a2318",
    muted: "#8a6a58",
    border: "#ecd9c9",
    accent: "#c2562c",
    accentText: "#ffffff",
    accentHover: "#a4451f",
    quote: "#fbeee3",
    radius: "1.75rem",
    avatarRadius: "999px",
    shadow: "0 22px 55px rgba(120, 70, 40, 0.12)",
    banner: "linear-gradient(120deg, #c2562c, #e39b6a 55%, #f6dcc4)",
    bannerHeight: "9.5rem",
    display: "var(--font-display), Georgia, serif",
    headlineWeight: 600,
    headlineTracking: "-0.02em",
    headlineTransform: "none",
    eyebrow: "#b08f79",
  },
  {
    id: "menthe",
    label: "Menthe",
    description: "Vert doux et blanc. Frais, calme, épuré.",
    layout: "centered",
    page: "#f2f8f4",
    surface: "#ffffff",
    text: "#132019",
    muted: "#5f7a6b",
    border: "#dbeae1",
    accent: "#1f7a52",
    accentText: "#ffffff",
    accentHover: "#176040",
    quote: "#eef6f1",
    radius: "1.5rem",
    avatarRadius: "999px",
    shadow: "0 20px 50px rgba(30, 80, 60, 0.10)",
    banner: "linear-gradient(120deg, #1f7a52, #7fc9a3 58%, #dff0e7)",
    bannerHeight: "9rem",
    display: "inherit",
    headlineWeight: 700,
    headlineTracking: "-0.03em",
    headlineTransform: "none",
    eyebrow: "#7d9c8c",
  },
  {
    id: "neon",
    label: "Néon",
    description: "Noir mat et vert électrique. Audacieux, pour créateurs tech.",
    layout: "left",
    page: "#08090a",
    surface: "#101214",
    text: "#f2f5f3",
    muted: "#8b938e",
    border: "#1e2226",
    accent: "#c8ff4d",
    accentText: "#0b1000",
    accentHover: "#b2e63f",
    quote: "#16191c",
    radius: "0.75rem",
    avatarRadius: "0.75rem",
    shadow: "0 26px 70px rgba(0, 0, 0, 0.6)",
    banner: "linear-gradient(120deg, #101214, #1d2a18 55%, #46661f)",
    bannerHeight: "8rem",
    display: "inherit",
    headlineWeight: 800,
    headlineTracking: "-0.04em",
    headlineTransform: "none",
    eyebrow: "#78836f",
  },
];

// Palettes supplémentaires : mêmes jetons, valeurs curées une à une.
donationThemes.push(
  {
    id: "ivoire", label: "Ivoire", description: "Blanc cassé et gris doux. Neutre, intemporel.",
    layout: "centered", page: "#f7f6f3", surface: "#ffffff", text: "#1c1b19", muted: "#77736c",
    border: "#e7e4dd", accent: "#2f2d29", accentText: "#ffffff", accentHover: "#2f2d29",
    quote: "#f2f0eb", eyebrow: "#a9a49b", banner: "linear-gradient(120deg,#e7e3d9,#f4f2ec 60%,#ffffff)",
    radius: "1.5rem", avatarRadius: "999px",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "ardoise", label: "Ardoise", description: "Gris profond et blanc net. Sobre, professionnel.",
    layout: "left", page: "#eceef0", surface: "#ffffff", text: "#16191c", muted: "#697079",
    border: "#dde1e6", accent: "#2b3138", accentText: "#ffffff", accentHover: "#2b3138",
    quote: "#f1f3f5", eyebrow: "#98a0a9", banner: "linear-gradient(120deg,#2b3138,#5b646e 60%,#c3cad1)",
    radius: "1rem", avatarRadius: "1rem",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "safran", label: "Safran", description: "Jaune chaud et brun. Solaire, généreux.",
    layout: "centered", page: "#fffaf0", surface: "#ffffff", text: "#2e2410", muted: "#8a7550",
    border: "#f0e4cc", accent: "#d99206", accentText: "#231a05", accentHover: "#d99206",
    quote: "#fdf4e2", eyebrow: "#b9a077", banner: "linear-gradient(120deg,#d99206,#f2c66a 58%,#fdf0d5)",
    radius: "1.5rem", avatarRadius: "999px",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "indigo", label: "Indigo", description: "Bleu-violet et blanc. Calme et affirmé.",
    layout: "centered", page: "#f3f4fb", surface: "#ffffff", text: "#1b1c33", muted: "#6a6d8c",
    border: "#e0e2f2", accent: "#3d43c9", accentText: "#ffffff", accentHover: "#3d43c9",
    quote: "#f0f1fa", eyebrow: "#9598b5", banner: "linear-gradient(120deg,#3d43c9,#8a8ff0 58%,#dfe1fb)",
    radius: "1.5rem", avatarRadius: "999px",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "rubis", label: "Rubis", description: "Rouge profond sur crème. Intense, chaleureux.",
    layout: "left", page: "#fdf5f5", surface: "#ffffff", text: "#2b1113", muted: "#8c6265",
    border: "#f2dcdd", accent: "#a81c2b", accentText: "#ffffff", accentHover: "#a81c2b",
    quote: "#fbeeee", eyebrow: "#bb9295", banner: "linear-gradient(120deg,#a81c2b,#e07b84 58%,#fbe3e4)",
    radius: "1.5rem", avatarRadius: "1rem",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "var(--font-display), Georgia, serif",
    headlineWeight: 600, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "foret", label: "Forêt", description: "Vert sombre et lin. Naturel, posé.",
    layout: "left", page: "#f5f7f2", surface: "#ffffff", text: "#16241a", muted: "#5d7263",
    border: "#dde7dc", accent: "#2c5c3a", accentText: "#ffffff", accentHover: "#2c5c3a",
    quote: "#eff4ed", eyebrow: "#8fa494", banner: "linear-gradient(120deg,#2c5c3a,#7fae8b 58%,#dfeee2)",
    radius: "1.5rem", avatarRadius: "1rem",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "var(--font-display), Georgia, serif",
    headlineWeight: 600, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "nuit", label: "Nuit", description: "Noir bleuté et texte clair. Élégant, discret.",
    layout: "centered", page: "#0c0f14", surface: "#141922", text: "#eef2f7", muted: "#94a0b0",
    border: "#222a36", accent: "#7fb2ff", accentText: "#08121f", accentHover: "#7fb2ff",
    quote: "#1a212c", eyebrow: "#6d7a8b", banner: "linear-gradient(120deg,#141922,#25324a 58%,#3d5a8c)",
    radius: "1.5rem", avatarRadius: "999px",
    shadow: "0 26px 70px rgba(0,0,0,0.45)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "charbon", label: "Charbon", description: "Gris anthracite et orange. Moderne, contrasté.",
    layout: "left", page: "#111111", surface: "#191919", text: "#f2f0ee", muted: "#948f89",
    border: "#262626", accent: "#ff7a3d", accentText: "#1a0800", accentHover: "#ff7a3d",
    quote: "#202020", eyebrow: "#7a746e", banner: "linear-gradient(120deg,#191919,#3a2418 58%,#7a3f18)",
    radius: "1rem", avatarRadius: "1rem",
    shadow: "0 26px 70px rgba(0,0,0,0.45)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "perle", label: "Perle", description: "Rose poudré et blanc. Doux, féminin.",
    layout: "centered", page: "#fdf6f7", surface: "#ffffff", text: "#2a1d22", muted: "#8b6f78",
    border: "#f4e2e7", accent: "#c2537a", accentText: "#ffffff", accentHover: "#c2537a",
    quote: "#fcf0f3", eyebrow: "#c0a0aa", banner: "linear-gradient(120deg,#c2537a,#f0a8bf 58%,#fce6ec)",
    radius: "1.75rem", avatarRadius: "999px",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "lagon", label: "Lagon", description: "Turquoise et blanc. Frais, lumineux.",
    layout: "centered", page: "#f0fafb", surface: "#ffffff", text: "#0f2427", muted: "#5b8186",
    border: "#d7ecee", accent: "#0e8f9e", accentText: "#ffffff", accentHover: "#0e8f9e",
    quote: "#eaf7f8", eyebrow: "#8bb0b4", banner: "linear-gradient(120deg,#0e8f9e,#6fd0da 58%,#d9f2f5)",
    radius: "1.5rem", avatarRadius: "999px",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "sable", label: "Sable", description: "Beige et taupe. Minimal, apaisant.",
    layout: "left", page: "#f8f5f0", surface: "#ffffff", text: "#282318", muted: "#867e6e",
    border: "#e9e2d5", accent: "#8a7346", accentText: "#ffffff", accentHover: "#8a7346",
    quote: "#f4f0e8", eyebrow: "#b1a793", banner: "linear-gradient(120deg,#8a7346,#c9b78c 58%,#f0e8d8)",
    radius: "1.25rem", avatarRadius: "1rem",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "var(--font-display), Georgia, serif",
    headlineWeight: 600, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "prune", label: "Prune", description: "Violet sombre et rosé. Raffiné, nocturne.",
    layout: "centered", page: "#1a1020", surface: "#241630", text: "#f4eefa", muted: "#a998b5",
    border: "#33224a", accent: "#c98bff", accentText: "#1a0b26", accentHover: "#c98bff",
    quote: "#2c1c3b", eyebrow: "#8b7a99", banner: "linear-gradient(120deg,#241630,#46275e 58%,#7a4a9e)",
    radius: "1.75rem", avatarRadius: "999px",
    shadow: "0 26px 70px rgba(0,0,0,0.45)",
    bannerHeight: "9rem", display: "var(--font-display), Georgia, serif",
    headlineWeight: 600, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "cuivre", label: "Cuivre", description: "Brun cuivré et crème. Artisanal, riche.",
    layout: "left", page: "#faf4ee", surface: "#ffffff", text: "#2c1d12", muted: "#876954",
    border: "#eedfd0", accent: "#a35c28", accentText: "#ffffff", accentHover: "#a35c28",
    quote: "#f8eee3", eyebrow: "#b99c82", banner: "linear-gradient(120deg,#a35c28,#d99a63 58%,#f7e3cf)",
    radius: "1.5rem", avatarRadius: "1rem",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "var(--font-display), Georgia, serif",
    headlineWeight: 600, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "acier", label: "Acier", description: "Bleu-gris froid et blanc. Technique, net.",
    layout: "left", page: "#f2f5f8", surface: "#ffffff", text: "#131a22", muted: "#5f6f7f",
    border: "#dbe3eb", accent: "#2d6ea8", accentText: "#ffffff", accentHover: "#2d6ea8",
    quote: "#eef3f7", eyebrow: "#93a3b2", banner: "linear-gradient(120deg,#2d6ea8,#7fb0d9 58%,#dbe9f4)",
    radius: "0.75rem", avatarRadius: "1rem",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "citron", label: "Citron", description: "Jaune vif et noir. Énergique, pop.",
    layout: "centered", page: "#fffdf2", surface: "#ffffff", text: "#1b1a10", muted: "#7a775f",
    border: "#efeccf", accent: "#c9b200", accentText: "#1a1700", accentHover: "#c9b200",
    quote: "#fbf8df", eyebrow: "#a8a37f", banner: "linear-gradient(120deg,#c9b200,#f2e35c 58%,#fdf9d6)",
    radius: "1rem", avatarRadius: "999px",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "brume", label: "Brume", description: "Gris perle et bleu pâle. Très léger.",
    layout: "centered", page: "#f6f8fa", surface: "#ffffff", text: "#1d2226", muted: "#6d7880",
    border: "#e3e8ed", accent: "#5a7d95", accentText: "#ffffff", accentHover: "#5a7d95",
    quote: "#f1f4f7", eyebrow: "#a0a9b1", banner: "linear-gradient(120deg,#bcc9d4,#dde5ec 60%,#ffffff)",
    radius: "1.75rem", avatarRadius: "999px",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "ocre", label: "Ocre", description: "Terre jaune et brun foncé. Chaud, ancré.",
    layout: "left", page: "#fbf6ec", surface: "#ffffff", text: "#2d2311", muted: "#8a7750",
    border: "#eee0c6", accent: "#b8860b", accentText: "#ffffff", accentHover: "#b8860b",
    quote: "#f8f1e1", eyebrow: "#b8a480", banner: "linear-gradient(120deg,#b8860b,#e0b75c 58%,#f7ead2)",
    radius: "1.25rem", avatarRadius: "1rem",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "var(--font-display), Georgia, serif",
    headlineWeight: 600, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "corail", label: "Corail", description: "Rose-orangé et blanc. Vivant, accueillant.",
    layout: "centered", page: "#fff6f4", surface: "#ffffff", text: "#2c1a16", muted: "#8d6a62",
    border: "#f6dfd9", accent: "#e0563f", accentText: "#ffffff", accentHover: "#e0563f",
    quote: "#fdeeea", eyebrow: "#c39c93", banner: "linear-gradient(120deg,#e0563f,#f79b85 58%,#fde3dc)",
    radius: "1.75rem", avatarRadius: "999px",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "jade", label: "Jade", description: "Vert-bleu profond et ivoire. Serein.",
    layout: "centered", page: "#f2f7f6", surface: "#ffffff", text: "#12211f", muted: "#5c7a76",
    border: "#d8e8e5", accent: "#14776b", accentText: "#ffffff", accentHover: "#14776b",
    quote: "#ecf5f3", eyebrow: "#8dada8", banner: "linear-gradient(120deg,#14776b,#6cc0b3 58%,#dcf0ec)",
    radius: "1.5rem", avatarRadius: "999px",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "onyx", label: "Onyx", description: "Noir pur et gris clair. Radical, minimal.",
    layout: "left", page: "#000000", surface: "#0d0d0d", text: "#f5f5f5", muted: "#8f8f8f",
    border: "#1f1f1f", accent: "#ffffff", accentText: "#000000", accentHover: "#ffffff",
    quote: "#171717", eyebrow: "#707070", banner: "linear-gradient(120deg,#0d0d0d,#2b2b2b 58%,#555555)",
    radius: "0.5rem", avatarRadius: "1rem",
    shadow: "0 26px 70px rgba(0,0,0,0.45)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "lin", label: "Lin", description: "Écru et gris chaud. Discret, textile.",
    layout: "left", page: "#f9f7f4", surface: "#ffffff", text: "#24211c", muted: "#7d776d",
    border: "#e8e3db", accent: "#57514a", accentText: "#ffffff", accentHover: "#57514a",
    quote: "#f3f0ea", eyebrow: "#a8a298", banner: "linear-gradient(120deg,#d9d2c6,#eae5db 60%,#ffffff)",
    radius: "1.25rem", avatarRadius: "1rem",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "var(--font-display), Georgia, serif",
    headlineWeight: 600, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "cobalt", label: "Cobalt", description: "Bleu franc et blanc. Direct, confiant.",
    layout: "centered", page: "#f1f5fd", surface: "#ffffff", text: "#101a2c", muted: "#5e7a90",
    border: "#d9e4f7", accent: "#1857c4", accentText: "#ffffff", accentHover: "#1857c4",
    quote: "#ebf1fc", eyebrow: "#8ba0c2", banner: "linear-gradient(120deg,#1857c4,#6f9de8 58%,#dbe8fa)",
    radius: "1rem", avatarRadius: "999px",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "miel", label: "Miel", description: "Ambre doux et blanc cassé. Gourmand.",
    layout: "centered", page: "#fdf8ef", surface: "#ffffff", text: "#2d2413", muted: "#8b7752",
    border: "#f1e5cd", accent: "#c98a12", accentText: "#ffffff", accentHover: "#c98a12",
    quote: "#faf2e3", eyebrow: "#bba880", banner: "linear-gradient(120deg,#c98a12,#efbf65 58%,#fbedd5)",
    radius: "1.75rem", avatarRadius: "999px",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "var(--font-display), Georgia, serif",
    headlineWeight: 600, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "cendre", label: "Cendre", description: "Gris moyen et blanc. Neutre absolu.",
    layout: "left", page: "#f4f4f4", surface: "#ffffff", text: "#1a1a1a", muted: "#6e6e6e",
    border: "#e2e2e2", accent: "#3f3f3f", accentText: "#ffffff", accentHover: "#3f3f3f",
    quote: "#efefef", eyebrow: "#a0a0a0", banner: "linear-gradient(120deg,#3f3f3f,#8c8c8c 58%,#d8d8d8)",
    radius: "0.75rem", avatarRadius: "1rem",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "orchidee", label: "Orchidée", description: "Mauve clair et blanc. Délicat.",
    layout: "centered", page: "#faf6fd", surface: "#ffffff", text: "#241a2c", muted: "#7d6c8a",
    border: "#ebdff3", accent: "#8b4fc0", accentText: "#ffffff", accentHover: "#8b4fc0",
    quote: "#f6eefb", eyebrow: "#ab97b8", banner: "linear-gradient(120deg,#8b4fc0,#c493e8 58%,#f0e2fa)",
    radius: "1.75rem", avatarRadius: "999px",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "tabac", label: "Tabac", description: "Brun sombre et beige. Chaleureux, feutré.",
    layout: "left", page: "#1d1712", surface: "#27201a", text: "#f4ede4", muted: "#a99884",
    border: "#382e25", accent: "#d9a441", accentText: "#1d1405", accentHover: "#d9a441",
    quote: "#2f2720", eyebrow: "#8d7c68", banner: "linear-gradient(120deg,#27201a,#463829 58%,#7a5f3a)",
    radius: "1.25rem", avatarRadius: "1rem",
    shadow: "0 26px 70px rgba(0,0,0,0.45)",
    bannerHeight: "9rem", display: "var(--font-display), Georgia, serif",
    headlineWeight: 600, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "givre", label: "Givre", description: "Bleu glacier et blanc. Épuré, froid.",
    layout: "centered", page: "#f4fafd", surface: "#ffffff", text: "#12212b", muted: "#5c7784",
    border: "#d9e9f1", accent: "#2b7f9e", accentText: "#ffffff", accentHover: "#2b7f9e",
    quote: "#edf6fa", eyebrow: "#8fabb8", banner: "linear-gradient(120deg,#9fd0e3,#d6ecf5 60%,#ffffff)",
    radius: "1.5rem", avatarRadius: "999px",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "brique", label: "Brique", description: "Rouge terreux et crème. Solide, franc.",
    layout: "left", page: "#fbf5f2", surface: "#ffffff", text: "#2b1812", muted: "#87635a",
    border: "#f0dcd4", accent: "#9c3b22", accentText: "#ffffff", accentHover: "#9c3b22",
    quote: "#f9ece7", eyebrow: "#b79287", banner: "linear-gradient(120deg,#9c3b22,#cf7a5e 58%,#f7e0d6)",
    radius: "1.25rem", avatarRadius: "1rem",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "var(--font-display), Georgia, serif",
    headlineWeight: 600, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "olive", label: "Olive", description: "Vert kaki et lin. Sobre, naturel.",
    layout: "left", page: "#f7f8f2", surface: "#ffffff", text: "#20240f", muted: "#6f7857",
    border: "#e3e8d3", accent: "#5c6b2b", accentText: "#ffffff", accentHover: "#5c6b2b",
    quote: "#f1f4e9", eyebrow: "#9aa383", banner: "linear-gradient(120deg,#5c6b2b,#a3b270 58%,#e6edd6)",
    radius: "1.25rem", avatarRadius: "1rem",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "var(--font-display), Georgia, serif",
    headlineWeight: 600, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "magenta", label: "Magenta", description: "Rose vif et noir. Audacieux, pop.",
    layout: "centered", page: "#fff5fa", surface: "#ffffff", text: "#25101b", muted: "#8a6072",
    border: "#f6d9e7", accent: "#d81b7a", accentText: "#ffffff", accentHover: "#d81b7a",
    quote: "#fdeaf3", eyebrow: "#c395ac", banner: "linear-gradient(120deg,#d81b7a,#f581b6 58%,#fde0ee)",
    radius: "1.5rem", avatarRadius: "999px",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "graphite", label: "Graphite", description: "Gris foncé et vert d'eau. Technique, calme.",
    layout: "left", page: "#15181a", surface: "#1d2124", text: "#eef1f2", muted: "#8e989c",
    border: "#2a3034", accent: "#5fd3c4", accentText: "#08201d", accentHover: "#5fd3c4",
    quote: "#232a2e", eyebrow: "#727c80", banner: "linear-gradient(120deg,#1d2124,#25403d 58%,#2f6b63)",
    radius: "0.75rem", avatarRadius: "1rem",
    shadow: "0 26px 70px rgba(0,0,0,0.45)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "papier", label: "Papier", description: "Blanc papier et encre noire. Livre ouvert.",
    layout: "left", page: "#fcfbf7", surface: "#ffffff", text: "#141310", muted: "#6f6b62",
    border: "#e6e3d9", accent: "#141310", accentText: "#ffffff", accentHover: "#141310",
    quote: "#f5f3ec", eyebrow: "#a29d92", banner: "linear-gradient(120deg,#e8e5da,#f6f4ee 60%,#ffffff)",
    radius: "0.5rem", avatarRadius: "1rem",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "var(--font-display), Georgia, serif",
    headlineWeight: 600, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "azur", label: "Azur", description: "Bleu ciel et blanc. Ouvert, aérien.",
    layout: "centered", page: "#f2f9ff", surface: "#ffffff", text: "#10202e", muted: "#5a7d98",
    border: "#d8e9f7", accent: "#0e7ac9", accentText: "#ffffff", accentHover: "#0e7ac9",
    quote: "#ebf5fd", eyebrow: "#8cacc4", banner: "linear-gradient(120deg,#0e7ac9,#74b9ec 58%,#d9ecfa)",
    radius: "1.75rem", avatarRadius: "999px",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "rouille", label: "Rouille", description: "Orange oxydé et gris. Industriel.",
    layout: "left", page: "#f8f5f3", surface: "#ffffff", text: "#241a15", muted: "#7d6b61",
    border: "#e9ded7", accent: "#b5541f", accentText: "#ffffff", accentHover: "#b5541f",
    quote: "#f5ece6", eyebrow: "#ab948a", banner: "linear-gradient(120deg,#b5541f,#dd8f5e 58%,#f6e2d4)",
    radius: "0.75rem", avatarRadius: "1rem",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "velours", label: "Velours", description: "Bordeaux profond et or pâle. Luxueux.",
    layout: "centered", page: "#1b0f14", surface: "#25151c", text: "#f6ecef", muted: "#b1949d",
    border: "#3a222b", accent: "#d9b166", accentText: "#1d1204", accentHover: "#d9b166",
    quote: "#2e1c24", eyebrow: "#937982", banner: "linear-gradient(120deg,#25151c,#4a2734 58%,#7d4a2f)",
    radius: "1.75rem", avatarRadius: "999px",
    shadow: "0 26px 70px rgba(0,0,0,0.45)",
    bannerHeight: "9rem", display: "var(--font-display), Georgia, serif",
    headlineWeight: 600, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "ciment", label: "Ciment", description: "Béton clair et noir. Brut, direct.",
    layout: "left", page: "#efefed", surface: "#ffffff", text: "#121212", muted: "#6b6b68",
    border: "#dcdcd8", accent: "#242422", accentText: "#ffffff", accentHover: "#242422",
    quote: "#e9e9e5", eyebrow: "#9c9c98", banner: "linear-gradient(120deg,#b9b9b4,#d8d8d3 60%,#f2f2ef)",
    radius: "0.25rem", avatarRadius: "1rem",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "tropique", label: "Tropique", description: "Vert vif et jaune. Solaire, joyeux.",
    layout: "centered", page: "#f6fcf2", surface: "#ffffff", text: "#152311", muted: "#5e7a57",
    border: "#dcecd4", accent: "#2f9e44", accentText: "#ffffff", accentHover: "#2f9e44",
    quote: "#eef8e9", eyebrow: "#8fae87", banner: "linear-gradient(120deg,#2f9e44,#a9e34b 58%,#e9f7d6)",
    radius: "1.75rem", avatarRadius: "999px",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "nocturne", label: "Nocturne", description: "Bleu nuit et blanc froid. Sérieux.",
    layout: "left", page: "#0f1320", surface: "#171d2e", text: "#eef1f8", muted: "#9aa3b8",
    border: "#252d42", accent: "#8ea6ff", accentText: "#0a1024", accentHover: "#8ea6ff",
    quote: "#1e263a", eyebrow: "#737d94", banner: "linear-gradient(120deg,#171d2e,#2a3555 58%,#48598c)",
    radius: "1.25rem", avatarRadius: "1rem",
    shadow: "0 26px 70px rgba(0,0,0,0.45)",
    bannerHeight: "9rem", display: "inherit",
    headlineWeight: 700, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "rose-poudre", label: "Rose poudré", description: "Rose très clair et brun doux. Tendre.",
    layout: "centered", page: "#fdf8f6", surface: "#ffffff", text: "#2a1f1b", muted: "#89716a",
    border: "#f2e3dd", accent: "#b06a55", accentText: "#ffffff", accentHover: "#b06a55",
    quote: "#fbefea", eyebrow: "#bda49c", banner: "linear-gradient(120deg,#e8c3b6,#f6e2da 60%,#ffffff)",
    radius: "1.75rem", avatarRadius: "999px",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "var(--font-display), Georgia, serif",
    headlineWeight: 600, headlineTracking: "-0.03em", headlineTransform: "none",
  },
  {
    id: "emeraude", label: "Émeraude", description: "Vert joaillier et ivoire. Précieux.",
    layout: "centered", page: "#f1f7f3", surface: "#ffffff", text: "#0f1f17", muted: "#57786a",
    border: "#d7e8de", accent: "#0b7a4b", accentText: "#ffffff", accentHover: "#0b7a4b",
    quote: "#eaf4ee", eyebrow: "#8aa89a", banner: "linear-gradient(120deg,#0b7a4b,#5cc08c 58%,#daf0e3)",
    radius: "1.5rem", avatarRadius: "999px",
    shadow: "0 20px 52px rgba(60,50,40,0.10)",
    bannerHeight: "9rem", display: "var(--font-display), Georgia, serif",
    headlineWeight: 600, headlineTracking: "-0.03em", headlineTransform: "none",
  },
);

export const defaultThemeId = donationThemes[0].id;
export function themeById(id?: string | null) {
  return donationThemes.find(theme => theme.id === id) || donationThemes[0];
}

export type DonationDesign = {
  page_theme: string;
  banner_url: string;
  page_eyebrow: string;
  page_headline: string;
  page_tagline: string;
  page_cta: string;
  page_note: string;
};

// Limites alignées sur celles appliquées côté API.
export const donationTextLimits: Record<keyof Omit<DonationDesign, "page_theme" | "banner_url">, number> = {
  page_eyebrow: 40,
  page_headline: 70,
  page_tagline: 180,
  page_cta: 40,
  page_note: 60,
};

/** Valeurs affichées quand le créateur n'a rien personnalisé. */
export function donationDefaults(displayName: string): DonationDesign {
  return {
    page_theme: defaultThemeId,
    banner_url: "",
    page_eyebrow: "Page de soutien",
    page_headline: `Soutenir ${displayName}`,
    page_tagline: "Soutiens son travail et ses prochaines créations.",
    page_cta: "Faire un Buy Me Data",
    page_note: "Paiement sécurisé",
  };
}

/** Complète les champs vides par les valeurs par défaut. */
export function resolveDonationDesign(displayName: string, stored?: Partial<DonationDesign> | null): DonationDesign {
  const defaults = donationDefaults(displayName);
  const entries = Object.entries(defaults).map(([key, fallback]) => {
    const value = stored?.[key as keyof DonationDesign];
    // La valeur n'est pas rognée ici : pendant la saisie, cela empêcherait de
    // taper une espace en fin de texte. Le nettoyage se fait à l'écriture.
    return [key, typeof value === "string" && value.trim() ? value : fallback];
  });
  const resolved = Object.fromEntries(entries) as DonationDesign;
  resolved.page_theme = themeById(resolved.page_theme).id;
  resolved.banner_url = typeof stored?.banner_url === "string" ? stored.banner_url : "";
  return resolved;
}

/** N'accepte que des images : URL distante, chemin local ou envoi direct. */
export function safeBannerUrl(value: string) {
  if (!value) return "";
  if (value.startsWith("/")) return value;
  // Bannière envoyée depuis l'éditeur, encodée comme l'avatar.
  if (/^data:image\/(png|jpeg|jpg|webp|gif);base64,[a-z0-9+/=]+$/i.test(value)) return value;
  try {
    const url = new URL(value);
    return url.protocol === "https:" || url.protocol === "http:" ? url.toString() : "";
  } catch {
    return "";
  }
}
