"use client";
import {useState} from "react";
import Link from "next/link";
import {TopUpLogo} from "@/components/Navbar";
export default function ResetPassword(){
 const [password,setPassword]=useState(""),[confirmation,setConfirmation]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setError("");if(password!==confirmation){setError("Les mots de passe ne correspondent pas.");return;}const token=new URLSearchParams(location.hash.slice(1)).get("token")||"";setBusy(true);try{const r=await fetch("/api/auth/reset-password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({token,password})});const d=await r.json();if(!r.ok)throw new Error(d.error);history.replaceState(null,"",location.pathname);setMessage("Votre mot de passe a été modifié. Vous pouvez vous connecter.");}catch(e){setError(e instanceof Error?e.message:"Veuillez réessayer.");}finally{setBusy(false);}}
 return <main className="grid min-h-screen place-items-center bg-[#fbf9f4] p-5"><section className="w-full max-w-md rounded-3xl border border-[#ead6d2] bg-white p-7 shadow-xl sm:p-9"><Link href="/" className="mb-8 flex items-center gap-3 font-bold text-[#b20024]"><TopUpLogo className="h-10 w-10"/>Buy Me Data</Link><h1 className="text-3xl font-bold">Nouveau mot de passe</h1><p className="mt-2 text-sm text-[#6f5a57]">Choisissez au moins 8 caractères.</p>{message&&<p role="status" className="mt-5 rounded-xl bg-[#edf6ee] p-4 text-sm text-[#315c38]">{message} <Link href="/login" className="font-bold underline">Se connecter</Link></p>}{error&&<p role="alert" className="mt-5 rounded-xl bg-[#fff2f1] p-4 text-sm text-[#b20024]">{error}</p>}{!message&&<form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-xs font-bold uppercase tracking-wider text-[#5b403f]">Nouveau mot de passe<input required minLength={8} maxLength={256} type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-2 w-full rounded-xl border border-[#e4bdbc] bg-[#fbf9f4] px-4 py-3.5 text-sm"/></label><label className="block text-xs font-bold uppercase tracking-wider text-[#5b403f]">Confirmer<input required minLength={8} maxLength={256} type="password" autoComplete="new-password" value={confirmation} onChange={e=>setConfirmation(e.target.value)} className="mt-2 w-full rounded-xl border border-[#e4bdbc] bg-[#fbf9f4] px-4 py-3.5 text-sm"/></label><button disabled={busy} className="w-full rounded-xl bg-[#b20024] px-4 py-4 font-bold text-white disabled:opacity-50">{busy?"Modification…":"Modifier le mot de passe"}</button></form>}</section></main>;
}
