"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import BrandSelect from "@/components/BrandSelect";
type Campaign={id:string;slug?:string;title:string;description?:string;cover_url?:string;target_amount:number;collected_amount:number;status:string;creator_name:string};
export default function Explore(){
 const [items,setItems]=useState<Campaign[]>([]),[status,setStatus]=useState("active"),[search,setSearch]=useState(""),[offset,setOffset]=useState(0),[more,setMore]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{const controller=new AbortController();const timer=setTimeout(async()=>{setLoading(true);setError("");try{const r=await fetch("/api/explore?"+new URLSearchParams({status,q:search,offset:String(offset)}),{signal:controller.signal});const d=await r.json();if(!r.ok)throw new Error(d.error);setItems(d.campaigns);setMore(d.hasMore);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"Chargement impossible.");}finally{if(!controller.signal.aborted)setLoading(false);}},250);return()=>{clearTimeout(timer);controller.abort();};},[status,search,offset]);
 return <><Navbar/><main className="mx-auto max-w-6xl px-5 py-12 sm:py-16"><header className="max-w-2xl"><p className="text-sm font-bold text-[#b20024]">Des projets, une communauté</p><h1 className="mt-3 text-4xl font-extrabold">Explorer les cagnottes</h1><p className="mt-4 leading-7 text-[#6f5a57]">Découvrez les objectifs des créateurs et aidez-les à rester connectés pour continuer à publier.</p></header>
 <div className="my-8 flex flex-col gap-4 sm:flex-row"><input aria-label="Rechercher une cagnotte" placeholder="Rechercher une cagnotte…" className="min-w-0 flex-1 rounded-xl border border-[#e4bdbc] bg-white px-4 py-3" value={search} onChange={e=>{setSearch(e.target.value);setOffset(0);}}/><BrandSelect label="Statut des cagnottes" value={status} onChange={value=>{setStatus(value);setOffset(0);}} options={[{value:"active",label:"En cours"},{value:"completed",label:"Financées"}]}/></div>
 <div aria-live="polite">{loading?<p className="py-16 text-center">Chargement des cagnottes…</p>:error?<p role="alert" className="py-16 text-center text-[#b20024]">{error}</p>:items.length===0?<p className="rounded-2xl border border-dashed border-[#e4bdbc] p-12 text-center text-[#6f5a57]">Aucune cagnotte ne correspond à votre recherche.</p>:<div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{items.map(c=>{const percent=Number(c.target_amount)>0?Math.min(100,Math.round(Number(c.collected_amount)*100/Number(c.target_amount))):0;return <article key={c.id} className="overflow-hidden rounded-2xl border border-[#ead6d2] bg-white"><img src={c.cover_url||"/buy-me-data-mascot.png"} alt="" className={"h-44 w-full bg-[#fff2f1] "+(c.cover_url?"object-cover":"object-contain p-10")}/><div className="p-5"><span className="text-xs font-bold text-[#b20024]">{c.status==="completed"?"Objectif financé":"En cours"}</span><h2 className="mt-2 text-xl font-bold">{c.title}</h2><p className="mt-1 text-xs text-[#6f5a57]">Par {c.creator_name}</p><p className="mt-4 line-clamp-3 text-sm leading-6 text-[#6f5a57]">{c.description}</p><div role="progressbar" aria-label="Objectif financé" aria-valuemin={0} aria-valuemax={100} aria-valuenow={percent} className="mt-5 h-2 overflow-hidden rounded-full bg-[#f1e4df]"><div className="h-full bg-[#b20024]" style={{width:percent+"%"}}/></div><p className="mt-2 text-xs text-[#6f5a57]">{Number(c.collected_amount).toLocaleString("fr-FR")} / {Number(c.target_amount).toLocaleString("fr-FR")} FCFA · {percent}%</p><Link className="mt-5 block rounded-xl bg-[#b20024] p-3 text-center text-sm font-bold text-white" href={"/c/"+(c.slug||c.id)}>{c.status==="completed"?"Voir la cagnotte":"Découvrir et soutenir"}</Link></div></article>;})}</div>}</div>
 {!loading&&!error&&<div className="mt-8 flex justify-center gap-6">{offset>0&&<button onClick={()=>setOffset(Math.max(0,offset-24))}>← Précédent</button>}{more&&<button onClick={()=>setOffset(offset+24)}>Suivant →</button>}</div>}
 </main><Footer/></>;
}
