"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

type Campaign={id:string;title:string;description?:string;target_amount:number|string;collected_amount:number|string;status:string};
type Creator={id:string;name:string;avatar_url?:string;role:string;username?:string;bio?:string;category?:string;campaigns:Campaign[]};

export default function ExplorePage(){
  const [creators,setCreators]=useState<Creator[]>([]); const [query,setQuery]=useState(""); const [loading,setLoading]=useState(true);
  useEffect(()=>{fetch("/api/creators",{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(d=>setCreators(d.creators||[])).finally(()=>setLoading(false));},[]);
  const filtered=useMemo(()=>creators.filter(c=>`${c.name} ${c.category||""} ${c.bio||""}`.toLowerCase().includes(query.toLowerCase())),[creators,query]);
  return <><Navbar/><main>
    <section className="border-b border-[#efe3df] bg-[#fbf9f4]"><div className="mx-auto max-w-6xl px-5 py-16 text-center sm:py-24"><span className="inline-flex rounded-full bg-[#ffdad8] px-3 py-1 text-xs font-bold text-[#8e001d]">Soutenir les créateurs, simplement</span><h1 className="mx-auto mt-5 max-w-3xl text-4xl font-bold tracking-tight text-[#1b1c19] sm:text-6xl">Un merci qui aide vraiment à créer.</h1><p className="mx-auto mt-5 max-w-xl text-base leading-7 text-[#6f5a57]">Découvrez un créateur, choisissez un montant et laissez un message. C’est tout.</p><div className="mx-auto mt-8 flex max-w-xl gap-2 rounded-2xl border border-[#ead6d2] bg-white p-2 shadow-sm"><span className="material-symbols-outlined self-center pl-2 text-[#8b7773]">search</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher un créateur" className="min-w-0 flex-1 bg-transparent px-2 py-2 text-sm outline-none"/></div></div></section>
    <section className="mx-auto max-w-6xl px-5 py-12 sm:py-16"><div className="mb-7 flex items-end justify-between"><div><h2 className="text-2xl font-bold text-[#1b1c19]">Créateurs</h2><p className="mt-1 text-sm text-[#6f5a57]">Uniquement des profils réellement inscrits.</p></div></div>
      {loading?<div className="py-16 text-center text-sm text-[#6f5a57]">Chargement…</div>:filtered.length===0?<div className="rounded-2xl border border-dashed border-[#dec9c4] bg-white px-6 py-16 text-center"><img src="/buy-me-data-mascot.png" alt="" className="mx-auto h-16 w-16 object-contain"/><h3 className="mt-4 font-bold text-[#1b1c19]">Aucun créateur publié</h3><p className="mt-2 text-sm text-[#6f5a57]">Les profils complétés apparaîtront ici.</p><Link href="/signup" className="mt-5 inline-block rounded-xl bg-[#b20024] px-5 py-3 text-sm font-bold text-white">Créer mon profil</Link></div>:<div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(c=><CreatorCard key={c.id} creator={c}/>)}</div>}
    </section>
    <section className="bg-[#1b1c19] text-white"><div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-6 px-5 py-12 text-center sm:flex-row sm:text-left"><div><h2 className="text-2xl font-bold">Vous créez du contenu ?</h2><p className="mt-2 text-sm text-white/65">Créez votre page en quelques minutes.</p></div><Link href="/signup" className="rounded-xl bg-white px-6 py-3 text-sm font-bold text-[#1b1c19]">Commencer</Link></div></section>
  </main><Footer/></>;
}

function CreatorCard({creator}:{creator:Creator}){const campaign=creator.campaigns?.[0];const total=Number(campaign?.target_amount||0),current=Number(campaign?.collected_amount||0),pct=total?Math.min(100,Math.round(current*100/total)):0;const payUrl=`/pay?creator_id=${creator.id}${campaign?`&campaign_id=${campaign.id}`:""}`;return <article className="overflow-hidden rounded-2xl border border-[#ead6d2] bg-white transition hover:-translate-y-1 hover:shadow-lg"><div className="flex items-center gap-4 p-5"><img src={creator.avatar_url||"/buy-me-data-mascot.png"} alt={creator.name} className="h-14 w-14 rounded-2xl bg-[#fff2f1] object-cover"/><div className="min-w-0"><h3 className="truncate font-bold text-[#1b1c19]">{creator.name}</h3><p className="truncate text-xs text-[#6f5a57]">{creator.category||"Créateur"}</p></div></div><div className="px-5 pb-5">{creator.bio&&<p className="mb-4 line-clamp-2 text-sm leading-6 text-[#6f5a57]">{creator.bio}</p>}{campaign?<div className="rounded-xl bg-[#fbf9f4] p-4"><div className="flex justify-between gap-3 text-xs"><span className="truncate font-semibold">{campaign.title}</span><span className="font-bold text-[#b20024]">{pct}%</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#eadfdb]"><div className="h-full bg-[#b20024]" style={{width:`${pct}%`}}/></div></div>:<p className="rounded-xl bg-[#fbf9f4] p-4 text-xs text-[#7b6864]">Aucune cagnotte active.</p>}<Link href={payUrl} className="mt-4 block rounded-xl bg-[#b20024] px-4 py-3 text-center text-sm font-bold text-white">Soutenir</Link></div></article>}
