"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
// The dashboard layout owns the persistent application header.
const Navbar = () => null;

type Profile = { id:string; email:string; full_name:string; role:"creator"|"supporter"; avatar_url?:string; username?:string; bio?:string; category?:string };
type Campaign = { id:string; title:string; current:number|string; total:number|string; status:string };
type Activity = { id:string; name:string; message?:string; amount:number|string };
type Support = { id:string; creator_name:string; creator_avatar?:string; amount:number|string; currency:string; status:string; created_at:string; message?:string };

export default function DashboardPage() {
  const [profile,setProfile]=useState<Profile|null>(null);
  const [campaigns,setCampaigns]=useState<Campaign[]>([]);
  const [activity,setActivity]=useState<Activity[]>([]);
  const [stats,setStats]=useState({collected:0,last30:0,last90:0,supporters:0,available:0,directSupport:0,campaignSupport:0});
  const [supports,setSupports]=useState<Support[]>([]);
  const [loading,setLoading]=useState(true);
  const [copied,setCopied]=useState(false);
  const [period,setPeriod]=useState<"30"|"90"|"all">("30");

  const load=async()=>{
    const [p,d]=await Promise.all([fetch("/api/profile",{cache:"no-store"}),fetch("/api/dashboard",{cache:"no-store"})]);
    if(p.status===401){location.href="/login";return;}
    const pp=await p.json(); const dd=d.ok?await d.json():{};
    setProfile(pp.profile); setCampaigns(dd.campaigns||[]); setActivity(dd.activity||[]);
    setSupports(dd.supports||[]);
    setStats({collected:Number(dd.stats?.collected||0),last30:Number(dd.stats?.last30||0),last90:Number(dd.stats?.last90||0),supporters:Number(dd.stats?.supporters||0),available:Number(dd.stats?.available||0),directSupport:Number(dd.stats?.direct_support||0),campaignSupport:Number(dd.stats?.campaign_support||0)}); setLoading(false);
  };
  useEffect(()=>{const timer=window.setTimeout(()=>{load().catch(()=>setLoading(false));},0);return()=>window.clearTimeout(timer);},[]);
  const publicUrl=profile?.username ? `https://buymedata.tools-cl.com/${profile.username}` : "";
  const periodValue=period==="30"?stats.last30:period==="90"?stats.last90:stats.collected;
  async function copyPublicLink(){if(!publicUrl)return;await navigator.clipboard?.writeText(publicUrl);setCopied(true);window.setTimeout(()=>setCopied(false),1800);}


  if(loading)return <><Navbar/><main className="mx-auto max-w-6xl px-5 py-20 text-center text-[#6f5a57]">Chargement de votre espace…</main></>;
  if(!profile)return null;
  if(profile.role==="supporter")return <><Navbar/><main className="mx-auto max-w-5xl px-5 py-10"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-[#b20024]">Votre espace soutien</p><h1 className="mt-2 text-3xl font-bold">Bonjour, {profile.full_name||profile.email.split("@")[0]}</h1><p className="mt-2 text-sm text-[#6f5a57]">Retrouvez uniquement vos contributions réelles.</p></div><Link href="/explore" className="rounded-xl bg-[#b20024] px-5 py-3 text-center text-sm font-bold text-white">Découvrir des créateurs</Link></header><section className="mt-8 grid gap-4 sm:grid-cols-2"><Metric label="Total soutenu" value={`${stats.collected.toLocaleString("fr-FR")} FCFA`}/><Metric label="Paiements réussis" value={String(stats.supporters)}/></section><section className="mt-8 rounded-2xl border border-[#ead6d2] bg-white p-5 sm:p-7"><h2 className="text-xl font-bold">Mes soutiens</h2><div className="mt-5 space-y-3">{supports.length===0?<Empty text="Vous n’avez encore soutenu aucun créateur."/>:supports.map(s=><div key={s.id} className="flex items-center gap-4 rounded-xl bg-[#fbf9f4] p-4"><img src={s.creator_avatar||"/buy-me-data-mascot.png"} alt="" className="h-11 w-11 rounded-xl object-cover"/><div className="min-w-0 flex-1"><p className="truncate font-semibold">{s.creator_name}</p><p className="text-xs text-[#7b6864]">{new Date(s.created_at).toLocaleDateString("fr-FR")} · {s.status}</p></div><p className="font-bold text-[#b20024]">{Number(s.amount).toLocaleString("fr-FR")} FCFA</p></div>)}</div></section></main></>;
  return <><Navbar/><div className="min-h-[calc(100vh-4rem)] bg-[#f5f3ee]"><DashboardSidebar profile={profile}/><main className="mx-auto min-w-0 max-w-[1260px] px-5 py-7 sm:px-8 lg:ml-[calc(16rem+2rem)] lg:mr-8 lg:max-w-none lg:px-0">
    <header className="mb-5 rounded-2xl border border-[#ead6d2] bg-white p-5 shadow-[0_10px_24px_rgba(91,64,63,0.05)] sm:p-6"><div className="flex items-center justify-between gap-4"><div className="flex min-w-0 items-center gap-4"><img src={profile.avatar_url||"/buy-me-data-mascot.png"} alt="" className="h-14 w-14 rounded-2xl bg-[#fff2f1] object-cover"/><div className="min-w-0"><h1 className="text-lg font-bold text-[#1b1c19]">Bonjour, {(profile.full_name||profile.email.split("@")[0]).split(" ")[0]}</h1><p className="mt-1 truncate text-sm text-[#6f5a57]">{publicUrl||"Choisissez votre lien public dans Mon compte"}</p></div></div><div className="flex gap-2"><button onClick={copyPublicLink} disabled={!publicUrl} aria-label="Copier le lien de ma page" className="grid h-11 w-11 place-items-center rounded-full bg-[#1b1c19] text-white disabled:opacity-40"><span className="material-symbols-outlined text-[20px]">{copied?"check":"ios_share"}</span></button><Link href={profile.username?`/${profile.username}`:"/dashboard/settings"} target="_blank" aria-label="Voir ma page" className="grid h-11 w-11 place-items-center rounded-full border border-[#b20024] text-[#b20024]"><span className="material-symbols-outlined text-[20px]">open_in_new</span></Link></div></div></header>
    <section className="mb-5 rounded-2xl border border-[#ead6d2] bg-white p-5 shadow-[0_10px_24px_rgba(91,64,63,0.05)] sm:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><h2 className="text-xl font-bold text-[#1b1c19]">Revenus</h2><select value={period} onChange={e=>setPeriod(e.target.value as "30"|"90"|"all")} className="rounded-xl border border-[#ead6d2] bg-white px-3 py-2 text-sm font-semibold text-[#5b403f] outline-none"><option value="30">30 derniers jours</option><option value="90">90 derniers jours</option><option value="all">Depuis toujours</option></select></div><p className="mt-5 text-4xl font-bold tracking-tight text-[#1b1c19]">{periodValue.toLocaleString("fr-FR")} FCFA</p><div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-xs text-[#6f5a57]"><span><i className="mr-2 inline-block h-2.5 w-2.5 rounded-sm bg-[#b20024]"/>Soutiens directs · {stats.directSupport.toLocaleString("fr-FR")} FCFA</span><span><i className="mr-2 inline-block h-2.5 w-2.5 rounded-sm bg-[#e8b7b0]"/>Cagnottes · {stats.campaignSupport.toLocaleString("fr-FR")} FCFA</span></div></section>
    <section className="grid gap-5 lg:grid-cols-3"><Link href="/dashboard/campaigns" className="rounded-2xl border border-[#ead6d2] bg-white p-6 shadow-[0_10px_24px_rgba(91,64,63,0.05)] transition hover:-translate-y-0.5"><span className="material-symbols-outlined text-[#b20024]">flag</span><h2 className="mt-4 text-xl font-bold">Cagnottes</h2><p className="mt-2 text-sm text-[#6f5a57]">{campaigns.length} objectif{campaigns.length!==1?"s":""} · créer, modifier et partager.</p><span className="mt-5 inline-block text-sm font-bold text-[#b20024]">Gérer mes cagnottes →</span></Link><Link href={profile.username?`/${profile.username}`:"/dashboard/settings"} className="rounded-2xl border border-[#ead6d2] bg-white p-6 shadow-[0_10px_24px_rgba(91,64,63,0.05)] transition hover:-translate-y-0.5"><span className="material-symbols-outlined text-[#b20024]">volunteer_activism</span><h2 className="mt-4 text-xl font-bold">Don personnel</h2><p className="mt-2 text-sm text-[#6f5a57]">Partagez votre profil pour recevoir des soutiens libres.</p><span className="mt-5 inline-block text-sm font-bold text-[#b20024]">Voir mon profil →</span></Link><Link href="/dashboard/withdrawals" className="rounded-2xl border border-[#ead6d2] bg-white p-6 shadow-[0_10px_24px_rgba(91,64,63,0.05)] transition hover:-translate-y-0.5"><span className="material-symbols-outlined text-[#b20024]">payments</span><h2 className="mt-4 text-xl font-bold">Retraits</h2><p className="mt-2 text-sm text-[#6f5a57]">{stats.available.toLocaleString("fr-FR")} FCFA disponibles.</p><span className="mt-5 inline-block text-sm font-bold text-[#b20024]">Gérer mes retraits →</span></Link></section>
    <section className="mt-5 rounded-2xl border border-[#ead6d2] bg-white p-5 shadow-[0_10px_24px_rgba(91,64,63,0.05)] sm:p-6"><h2 className="font-bold text-[#1b1c19]">Derniers soutiens</h2><div className="mt-4 space-y-3">{activity.length===0?<Empty text="Vos prochains dons apparaîtront ici."/>:activity.slice(0,5).map(a=><div key={a.id} className="flex items-start justify-between gap-3 border-b border-[#f0e8e5] pb-3 last:border-0"><div><p className="text-sm font-semibold">{a.name}</p>{a.message&&<p className="mt-1 text-xs text-[#6f5a57]">{a.message}</p>}</div><span className="whitespace-nowrap text-xs font-bold text-[#315c38]">+{Number(a.amount).toLocaleString("fr-FR")} F</span></div>)}</div></section>
  </main></div></>;
}

function DashboardSidebar({profile}:{profile:Profile}){return <aside className="fixed inset-y-16 left-0 z-30 hidden w-64 border-r border-[#ead6d2] bg-white lg:block"><div className="flex h-full flex-col p-4"><img src="/buy-me-data-mascot.png" alt="Buy Me Data" className="ml-2 h-10 w-10 object-contain"/><nav className="mt-6 space-y-1"><SideLink href="/dashboard" icon="home" label="Accueil"/><SideLink href={profile.username?`/${profile.username}`:"/dashboard/settings"} icon="open_in_new" label="Voir ma page"/><p className="px-3 pb-2 pt-6 text-[10px] font-bold uppercase tracking-[0.16em] text-[#a18d88]">Monétiser</p><SideLink href="/dashboard/campaigns" icon="flag" label="Cagnottes"/><SideLink href="/dashboard/withdrawals" icon="payments" label="Retraits"/></nav></div></aside>}
function SideLink({href,icon,label}:{href:string;icon:string;label:string}){return <Link href={href} className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium text-[#1b1c19] transition hover:bg-[#f5f3ee]"><span className="material-symbols-outlined text-[19px]">{icon}</span>{label}</Link>}

function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-[#ead6d2] bg-white p-5 shadow-[0_10px_24px_rgba(91,64,63,0.06)]"><p className="text-xs font-semibold uppercase tracking-wide text-[#7b6864]">{label}</p><p className="mt-2 text-2xl font-bold text-[#1b1c19]">{value}</p></div>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed border-[#dec9c4] px-4 py-6 text-center text-xs text-[#7b6864]">{text}</div>}
