"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import Navbar from "@/components/Navbar";

type Profile = { id:string; email:string; full_name:string; role:"creator"|"supporter"; avatar_url?:string; username?:string; bio?:string; category?:string };
type Campaign = { id:string; title:string; current:number|string; total:number|string; status:string };
type Activity = { id:string; name:string; message?:string; amount:number|string };
type Withdrawal = { id:string; amount:number|string; fee_amount:number|string; net_amount:number|string; method:string; destination:string; status:string; created_at:string };
type Support = { id:string; creator_name:string; creator_avatar?:string; amount:number|string; currency:string; status:string; created_at:string; message?:string };
const input = "mt-2 w-full rounded-xl border border-[#ead6d2] bg-white px-4 py-3 text-sm outline-none focus:border-[#b20024] focus:ring-4 focus:ring-[#b20024]/10";

export default function DashboardPage() {
  const [profile,setProfile]=useState<Profile|null>(null);
  const [campaigns,setCampaigns]=useState<Campaign[]>([]);
  const [activity,setActivity]=useState<Activity[]>([]);
  const [stats,setStats]=useState({collected:0,last30:0,last90:0,supporters:0,available:0});
  const [withdrawals,setWithdrawals]=useState<Withdrawal[]>([]);
  const [supports,setSupports]=useState<Support[]>([]);
  const [loading,setLoading]=useState(true);
  const [saving,setSaving]=useState(false);
  const [notice,setNotice]=useState("");
  const [showCampaign,setShowCampaign]=useState(false);
  const [copied,setCopied]=useState(false);

  const load=async()=>{
    const [p,d]=await Promise.all([fetch("/api/profile",{cache:"no-store"}),fetch("/api/dashboard",{cache:"no-store"})]);
    if(p.status===401){location.href="/login";return;}
    const pp=await p.json(); const dd=d.ok?await d.json():{};
    setProfile(pp.profile); setCampaigns(dd.campaigns||[]); setActivity(dd.activity||[]);
    setWithdrawals(dd.withdrawals||[]); setSupports(dd.supports||[]);
    setStats({collected:Number(dd.stats?.collected||0),last30:Number(dd.stats?.last30||0),last90:Number(dd.stats?.last90||0),supporters:Number(dd.stats?.supporters||0),available:Number(dd.stats?.available||0)}); setLoading(false);
  };
  useEffect(()=>{const timer=window.setTimeout(()=>{load().catch(()=>setLoading(false));},0);return()=>window.clearTimeout(timer);},[]);
  const progress=useMemo(()=>profile?Math.round(([profile.full_name,profile.username,profile.bio,profile.avatar_url,campaigns.length].filter(Boolean).length/5)*100):0,[profile,campaigns]);
  const publicUrl=profile?.username ? `https://buymedata.tools-cl.com/${profile.username}` : "";
  async function copyPublicLink(){if(!publicUrl)return;await navigator.clipboard?.writeText(publicUrl);setCopied(true);window.setTimeout(()=>setCopied(false),1800);}

  async function createCampaign(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setNotice("");const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch("/api/campaigns",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await r.json();if(r.ok){setShowCampaign(false);setNotice("Cagnotte créée");await load();}else setNotice(data.error||"Création impossible");setSaving(false);}
  async function requestWithdrawal(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setNotice("");const body=Object.fromEntries(new FormData(e.currentTarget));const r=await fetch("/api/dashboard",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await r.json();if(r.ok){setNotice(`Demande enregistrée · ${Number(data.fees.net).toLocaleString("fr-FR")} FCFA nets après frais`);e.currentTarget.reset();await load();}else setNotice(data.error||"Retrait impossible");setSaving(false);}

  if(loading)return <><Navbar/><main className="mx-auto max-w-6xl px-5 py-20 text-center text-[#6f5a57]">Chargement de votre espace…</main></>;
  if(!profile)return null;
  if(profile.role==="supporter")return <><Navbar/><main className="mx-auto max-w-5xl px-5 py-10"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-[#b20024]">Votre espace soutien</p><h1 className="mt-2 text-3xl font-bold">Bonjour, {profile.full_name||profile.email.split("@")[0]}</h1><p className="mt-2 text-sm text-[#6f5a57]">Retrouvez uniquement vos contributions réelles.</p></div><Link href="/explore" className="rounded-xl bg-[#b20024] px-5 py-3 text-center text-sm font-bold text-white">Découvrir des créateurs</Link></header><section className="mt-8 grid gap-4 sm:grid-cols-2"><Metric label="Total soutenu" value={`${stats.collected.toLocaleString("fr-FR")} FCFA`}/><Metric label="Paiements réussis" value={String(stats.supporters)}/></section><section className="mt-8 rounded-2xl border border-[#ead6d2] bg-white p-5 sm:p-7"><h2 className="text-xl font-bold">Mes soutiens</h2><div className="mt-5 space-y-3">{supports.length===0?<Empty text="Vous n’avez encore soutenu aucun créateur."/>:supports.map(s=><div key={s.id} className="flex items-center gap-4 rounded-xl bg-[#fbf9f4] p-4"><img src={s.creator_avatar||"/buy-me-data-mascot.png"} alt="" className="h-11 w-11 rounded-xl object-cover"/><div className="min-w-0 flex-1"><p className="truncate font-semibold">{s.creator_name}</p><p className="text-xs text-[#7b6864]">{new Date(s.created_at).toLocaleDateString("fr-FR")} · {s.status}</p></div><p className="font-bold text-[#b20024]">{Number(s.amount).toLocaleString("fr-FR")} FCFA</p></div>)}</div></section></main></>;
  return <><Navbar/><main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 sm:py-12">
    <header className="mb-8 rounded-2xl border border-[#ead6d2] bg-white p-5 sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="mb-2 text-sm font-semibold text-[#b20024]">Votre espace créateur</p><h1 className="text-3xl font-bold tracking-tight text-[#1b1c19] sm:text-4xl">Bonjour, {profile.full_name||profile.email.split("@")[0]}</h1><p className="mt-2 text-sm text-[#6f5a57]">Gérez votre page, vos cagnottes et vos soutiens.</p></div><div className="flex flex-wrap gap-2"><Link href={profile.username?`/${profile.username}`:"/dashboard/settings"} target="_blank" className="rounded-xl border border-[#b20024] px-4 py-3 text-center text-sm font-bold text-[#b20024]">Voir ma page</Link><Link href="/dashboard/settings" className="rounded-xl bg-[#1b1c19] px-4 py-3 text-center text-sm font-bold text-white">Paramètres</Link></div></div>{profile.username&&<div className="mt-6 flex flex-col gap-3 rounded-xl bg-[#fbf9f4] p-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-wide text-[#7b6864]">Lien à partager</p><p className="mt-1 truncate text-sm font-semibold text-[#1b1c19]">{publicUrl}</p></div><button onClick={copyPublicLink} className="rounded-lg bg-[#b20024] px-4 py-2 text-sm font-bold text-white">{copied?"Copié !":"Copier le lien"}</button></div>}</header>
    {notice&&<div className="mb-6 rounded-xl bg-[#fff2f1] px-4 py-3 text-sm font-semibold text-[#8e001d]">{notice}</div>}
    <section className="mb-7 rounded-2xl border border-[#ead6d2] bg-white p-5 sm:p-6"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-bold text-[#1b1c19]">Mise en ligne de votre page</p><p className="mt-1 text-xs text-[#6f5a57]">Complétez les étapes pour recevoir des soutiens.</p></div><span className="text-lg font-bold text-[#b20024]">{progress}%</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-[#f2e8e5]"><div className="h-full rounded-full bg-[#b20024]" style={{width:`${progress}%`}}/></div><div className="mt-4 grid gap-2 text-xs sm:grid-cols-5">{[["Profil",profile.full_name],["Lien public",profile.username],["Présentation",profile.bio],["Photo",profile.avatar_url],["Cagnotte",campaigns.length]].map(([label,done])=><div key={String(label)} className={`rounded-lg px-3 py-2 ${done?"bg-[#edf6ee] text-[#315c38]":"bg-[#f7f4f1] text-[#7b6864]"}`}>{done?"✓ ":"○ "}{label}</div>)}</div></section>
    <section className="mb-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="30 derniers jours" value={`${stats.last30.toLocaleString("fr-FR")} FCFA`}/><Metric label="90 derniers jours" value={`${stats.last90.toLocaleString("fr-FR")} FCFA`}/><Metric label="Depuis toujours" value={`${stats.collected.toLocaleString("fr-FR")} FCFA`}/><Metric label="Disponible" value={`${stats.available.toLocaleString("fr-FR")} FCFA`}/></section>
    <div className="grid gap-7 lg:grid-cols-[1.15fr_.85fr]">
      <section className="rounded-2xl border border-[#ead6d2] bg-white p-5 sm:p-7"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-bold text-[#1b1c19]">Votre page de soutien</h2><p className="mt-1 text-sm text-[#6f5a57]">Le nom, la photo et la présentation se gèrent dans les paramètres.</p></div><Link href="/dashboard/settings" className="rounded-lg border border-[#b20024] px-3 py-2 text-xs font-bold text-[#b20024]">Modifier</Link></div><div className="mt-6 rounded-xl bg-[#fbf9f4] p-5"><p className="text-sm font-semibold">{profile.username?`buymedata.tools-cl.com/${profile.username}`:"Choisissez votre nom public"}</p><p className="mt-2 text-xs text-[#6f5a57]">Votre lien public est prêt à être partagé dès que votre page est complétée.</p></div></section>
      <aside className="space-y-7"><section className="rounded-2xl border border-[#ead6d2] bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><div><h2 className="font-bold text-[#1b1c19]">Cagnottes</h2><p className="mt-1 text-xs text-[#6f5a57]">Un objectif clair suffit.</p></div><button onClick={()=>setShowCampaign(v=>!v)} className="rounded-lg bg-[#b20024] px-3 py-2 text-xs font-bold text-white">{showCampaign?"Fermer":"Créer"}</button></div>{showCampaign&&<form onSubmit={createCampaign} className="mt-5 space-y-3"><input name="title" required minLength={3} placeholder="Nom de la cagnotte" className={input}/><textarea name="description" maxLength={500} rows={3} placeholder="À quoi servira ce soutien ?" className={`${input} resize-none`}/><input name="target_amount" required type="number" min={1000} placeholder="Objectif en FCFA" className={input}/><button disabled={saving} className="w-full rounded-xl bg-[#1b1c19] px-4 py-3 text-sm font-bold text-white">Créer la cagnotte</button></form>}<div className="mt-5 space-y-3">{campaigns.length===0?<Empty text="Aucune cagnotte pour le moment."/>:campaigns.map(c=><CampaignCard key={c.id} campaign={c}/>)}</div></section>
      <section className="rounded-2xl border border-[#ead6d2] bg-white p-5 sm:p-6"><h2 className="font-bold text-[#1b1c19]">Activité récente</h2><div className="mt-4 space-y-3">{activity.length===0?<Empty text="Les soutiens apparaîtront ici."/>:activity.slice(0,5).map(a=><div key={a.id} className="flex items-start justify-between gap-3 border-b border-[#f0e8e5] pb-3 last:border-0"><div><p className="text-sm font-semibold">{a.name}</p>{a.message&&<p className="mt-1 text-xs text-[#6f5a57]">{a.message}</p>}</div><span className="whitespace-nowrap text-xs font-bold text-[#315c38]">+{Number(a.amount).toLocaleString("fr-FR")} F</span></div>)}</div></section></aside>
    </div>
    <section className="mt-7 rounded-2xl border border-[#ead6d2] bg-white p-5 sm:p-7"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-xl font-bold">Retraits</h2><p className="mt-1 text-sm text-[#6f5a57]">Mobile Money ou crypto · frais Buy Me Data : 11 % du montant demandé.</p></div><span className="text-sm font-bold text-[#496546]">{stats.available.toLocaleString("fr-FR")} FCFA disponibles</span></div><form onSubmit={requestWithdrawal} className="mt-5 grid gap-3 sm:grid-cols-[.8fr_1fr_1.5fr_auto]"><input name="amount" type="number" min={500} max={stats.available||undefined} required placeholder="Montant" className={input}/><select name="method" className={input} defaultValue="mobile_money"><option value="mobile_money">Mobile Money</option><option value="crypto">Crypto</option></select><input name="destination" required placeholder="Numéro ou adresse du portefeuille" className={input}/><button disabled={saving||stats.available<500} className="mt-2 rounded-xl bg-[#1b1c19] px-5 py-3 text-sm font-bold text-white disabled:opacity-40">Demander</button></form><div className="mt-5 space-y-2">{withdrawals.length===0?<Empty text="Aucune demande de retrait."/>:withdrawals.map(w=><div key={w.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-[#fbf9f4] px-4 py-3 text-sm"><span>{w.method==="crypto"?"Crypto":"Mobile Money"} · {w.destination}</span><span className="font-semibold">{Number(w.net_amount || (Number(w.amount) * .89)).toLocaleString("fr-FR")} FCFA nets · {w.status}<small className="block text-xs font-normal text-[#7b6864]">Demande : {Number(w.amount).toLocaleString("fr-FR")} · frais : {Number(w.fee_amount || (Number(w.amount) * .11)).toLocaleString("fr-FR")}</small></span></div>)}</div></section>
  </main></>;
}

function Metric({label,value}:{label:string;value:string}){return <div className="rounded-2xl border border-[#ead6d2] bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-[#7b6864]">{label}</p><p className="mt-2 text-2xl font-bold text-[#1b1c19]">{value}</p></div>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed border-[#dec9c4] px-4 py-6 text-center text-xs text-[#7b6864]">{text}</div>}
function CampaignCard({campaign}:{campaign:Campaign}){const total=Number(campaign.total),current=Number(campaign.current),pct=total?Math.min(100,Math.round(current*100/total)):0;return <div className="rounded-xl bg-[#fbf9f4] p-4"><div className="flex justify-between gap-3"><p className="text-sm font-bold">{campaign.title}</p><span className="text-xs font-bold text-[#b20024]">{pct}%</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#eadfdb]"><div className="h-full bg-[#b20024]" style={{width:`${pct}%`}}/></div><p className="mt-2 text-xs text-[#6f5a57]">{current.toLocaleString("fr-FR")} / {total.toLocaleString("fr-FR")} FCFA</p></div>}
